name: mbah
description: "A new Flutter project."

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.2.17
  youtube_explode_dart: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
environment:
  sdk: '^3.2.0'